### ISSUE TITLE
Space through characters in profile file.

### ISSUE THREAD

**Issue by igzdan87** [irseny/RivaCross#1]
Hello, i'm trying RivaCross , and i want make a  profile file with multiple characters and a space between them... i want this [ + ] for example , but if i write in the config file , appear just the first character [  , instead if i use the window of rivacross and set a new char it register it correctly, then the question is, is possibile make a space in the profile file?

Another question, i'm usinig Afterburner + Rivatuner since years in every game for monitor my pc,  i want try this for fun, and i was wondering if there is any risk with some anti cheat software to detect it as a cheat... or it ill be injected in rivatuner and if it's already admitted there isn't any risk.

I can live without RivaCross but i just want try it a bit more without risk my game account in certain games. XD

Thank you in advance for responding

**Comment by irseny** [comment]
Hello,
sorry for not responding earlier. Although I'm checking the github page somewhat regularly I have somehow missed your message until looking through my past mails. 

Regarding the cheat detection, I cannot make any guarantees and you should be aware that your accounts might get banned for using this tool. Since we are writing to a 'publicly available' memory mapped region it is trivial for any other program to look up if there is any content in the respective shared memory space.

I have mostly tested this tool with offline titles, so I cannot really comment on experiences with online titles.

I have made a note for the whitespace character stuff and will most likely have time tomorrow to look into this. It is in my interest to extend the functionality for this tool where it can be done easily. Will report back then.

Edit: Merged messages

**Comment by irseny** [comment]
I have mostly tested this tool with offline titles, so I cannot really comment on experiences with online titles.

I have made a not for the whitespace character stuff and will most likely have time tomorrow to look into this.

**Comment by irseny** [comment]
The issue you found should be fixed in the source code now.
I will implement an additional feature tomorrow and upload the whole thing as new version plus executable.

**Comment by irseny** [comment]
Done. [Direct download of the updated application](https://github.com/irseny/RivaCross/releases/download/v0.5.1/RivaCross.Windows.64bit.zip)

I have been looking for reports on the detection in current anti cheat software for RTSS_Crosshair which depends on the same technological foundation as RivaCross. I was only able to find confirmation that the respective features of RTSS are not an issue for these anti cheat solutions.

From a more personal evaluation I would be cautious with more serious titles (Counter Strike)
